spring.application.name=gam-api

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.expiration-ms=3600000 # 1 hour
jwt.refresh-expiration-ms=604800000 # 7 days

app.auth.cookie.secure=false #dev
#app.auth.cookie.secure=false #prod
