spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-only

jwt.secret-key=ZmFrZS1kZXYtc2VjcmV0LWtleS1mb3ItZ2FtLWFwaS0zMi1ieXRlcw==

app.auth.cookie.secure=false
cors.allowed-origins=http://localhost:3000

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
